set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER "/bin/aarch64-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "/bin/aarch64-w64-mingw32-g++")
add_link_options(--static)
link_libraries(stdc++exp)