set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "/bin/x86_64-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "/bin/x86_64-w64-mingw32-g++")
add_link_options(--static)
link_libraries(stdc++exp)